name: fit-3bf
channels:
  - conda-forge
  - defaults
dependencies:
  - docrep=0.3.1
  - emcee=3.0.2
  - matplotlib=3.3.2
  - ncurses=6.2
  - numpy=1.19.2
  - numba=0.51.2
  - python=3.8.5
  - schwimmbad=0.3.1
  - scikit-learn=0.23.2
  - scipy=1.6.0
  - seaborn=0.11.1
  - pip:
      - corner==2.1.0
      - pydoe==0.3.8
      - hickle=4.0.4
      - json-tricks=3.15.5
      - ruamel.yaml